name: Awaria Outage Monitor
version: "1.0.62-alpha"
slug: awaria_outage_monitor
stage: experimental
description: Headless outage monitor for Polish utility providers (Tauron, PGE, Enea, Energa, MPWiK, Stoen, Veolia, etc.)
url: https://github.com/eremef/awaria-outage-notifier
image: "ghcr.io/eremef/awaria-outage-monitor"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8000
panel_icon: "mdi:power-plug-off"
panel_title: "Awaria"
homeassistant_api: true
services:
  - "mqtt:want"
ports:
  8000/tcp: 8000
options:
  addresses:
    - name: "Dom"
      cityName: "Warszawa"
      streetName: "Marszałkowska"
      houseNo: "1"
      isActive: true
  enabled_sources:
    - tauron
    - pge
    - stoen
    - mpwik_warszawa
  port: 8000
  show_other_outages: true
  check_interval_minutes: 60
schema:
  addresses:
    - name: str
      cityName: str
      streetName: str
      houseNo: str
      isActive: bool?
  enabled_sources:
    - list(tauron|mpwik_wroclaw|mpwik_warszawa|fortum|energa|enea|pge|stoen|wmk|tauron_heat|aquanet|katowickie_wodociagi|veolia_warszawa|veolia_poznan|veolia_lodz|zwik_lodz|wodociagi_plockie|pwik_czestochowa|gdanskie_wodociagi)
  port: port
  show_other_outages: bool
  check_interval_minutes: int
